### ISSUE TITLE
Form validation for 5 degree increments

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/Scisat-App#128]
I think using floor, rounding or ceiling in the background should be OK.

**Comment by emilinecsa** [comment]
This bug is fixed. Entering a wrong value shows this error message:
[Invalid values provided. Longitude values must be between -180 and 180. Minimum values must be smaller than maximum values. All values must be round numbers that are multiples of 5.](https://datatest.asc-csa.gc.ca:8888/scisat/#lon_alert)
TESTED on production on April 20th, 2023.
